
package si.feri.aiv.clansoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClanSoap", targetNamespace = "http://ClanSoap.aiv.feri.si/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClanSoap {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "vrniOsebo", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.VrniOsebo")
    @ResponseWrapper(localName = "vrniOseboResponse", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.VrniOseboResponse")
    public void vrniOsebo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "izbrisiOsebo", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.IzbrisiOsebo")
    @ResponseWrapper(localName = "izbrisiOseboResponse", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.IzbrisiOseboResponse")
    public void izbrisiOsebo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<si.feri.aiv.clansoap.OsebaClan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "vrniVseOsebe", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.VrniVseOsebe")
    @ResponseWrapper(localName = "vrniVseOsebeResponse", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.VrniVseOsebeResponse")
    public List<OsebaClan> vrniVseOsebe();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "spremeni", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.Spremeni")
    @ResponseWrapper(localName = "spremeniResponse", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.SpremeniResponse")
    public void spremeni(
        @WebParam(name = "arg0", targetNamespace = "")
        OsebaClan arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "dodajOsebo", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.DodajOsebo")
    @ResponseWrapper(localName = "dodajOseboResponse", targetNamespace = "http://ClanSoap.aiv.feri.si/", className = "si.feri.aiv.clansoap.DodajOseboResponse")
    public void dodajOsebo(
        @WebParam(name = "arg0", targetNamespace = "")
        OsebaClan arg0);

}
