
package si.feri.aiv.clansoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClanSoapService", targetNamespace = "http://ClanSoap.aiv.feri.si/", wsdlLocation = "http://localhost:8080/ArhitektureNaloge/ClanSoap?wsdl")
public class ClanSoapService
    extends Service
{

    private final static URL CLANSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLANSOAPSERVICE_EXCEPTION;
    private final static QName CLANSOAPSERVICE_QNAME = new QName("http://ClanSoap.aiv.feri.si/", "ClanSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ArhitektureNaloge/ClanSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLANSOAPSERVICE_WSDL_LOCATION = url;
        CLANSOAPSERVICE_EXCEPTION = e;
    }

    public ClanSoapService() {
        super(__getWsdlLocation(), CLANSOAPSERVICE_QNAME);
    }

    public ClanSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLANSOAPSERVICE_QNAME, features);
    }

    public ClanSoapService(URL wsdlLocation) {
        super(wsdlLocation, CLANSOAPSERVICE_QNAME);
    }

    public ClanSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLANSOAPSERVICE_QNAME, features);
    }

    public ClanSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClanSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClanSoap
     */
    @WebEndpoint(name = "ClanSoapPort")
    public ClanSoap getClanSoapPort() {
        return super.getPort(new QName("http://ClanSoap.aiv.feri.si/", "ClanSoapPort"), ClanSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClanSoap
     */
    @WebEndpoint(name = "ClanSoapPort")
    public ClanSoap getClanSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ClanSoap.aiv.feri.si/", "ClanSoapPort"), ClanSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLANSOAPSERVICE_EXCEPTION!= null) {
            throw CLANSOAPSERVICE_EXCEPTION;
        }
        return CLANSOAPSERVICE_WSDL_LOCATION;
    }

}
